# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Prettify code
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md}
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.X
    - name: Generate new package-lock.json
      run: npm i --package-lock-only
    - name: Commit new package-lock.json
      run: |
          git config user.name actions-user || :
          git config user.email actions-user@github.com || :
          git add . || :
          git commit -m "Updated package-lock.json" || :
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: prettier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.X
    - run: npm i
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test --if-present
